# Generated by Django 5.2 on 2025-06-01 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('wallet_address', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='crypto_logos/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Cryptocurrencies',
            },
        ),
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('vip', 'VIP'), ('platinum', 'Platinum'), ('gold', 'Gold')], max_length=50)),
                ('min_deposit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('max_deposit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('roi_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_days', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Trading Platform', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/logo/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('live_chat_enabled', models.BooleanField(default=False)),
                ('live_chat_script_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expected_return', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.investmentplan')),
            ],
        ),
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('passport', 'Passport'), ('drivers_license', "Driver's License"), ('national_id', 'National ID')], max_length=20)),
                ('id_number', models.CharField(max_length=50)),
                ('id_front', models.ImageField(null=True, upload_to='kyc_documents/')),
                ('id_back', models.ImageField(null=True, upload_to='kyc_documents/')),
                ('selfie', models.ImageField(null=True, upload_to='kyc_documents/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('investment', 'Investment'), ('profit', 'Profit Payment'), ('bonus', 'Bonus Payment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('crypto', 'Cryptocurrency'), ('internal', 'Internal Transfer')], max_length=20)),
                ('wallet_address', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cryptocurrency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.cryptocurrency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('NGN', 'Nigerian Naira (₦)'), ('GHS', 'Ghanaian Cedi (₵)'), ('KES', 'Kenyan Shilling (KSh)'), ('ZAR', 'South African Rand (R)'), ('AUD', 'Australian Dollar (A$)'), ('CAD', 'Canadian Dollar (C$)'), ('JPY', 'Japanese Yen (¥)'), ('CNY', 'Chinese Yuan (¥)'), ('INR', 'Indian Rupee (₹)'), ('KRW', 'South Korean Won (₩)'), ('SGD', 'Singapore Dollar (S$)'), ('HKD', 'Hong Kong Dollar (HK$)'), ('MYR', 'Malaysian Ringgit (RM)'), ('THB', 'Thai Baht (฿)'), ('PHP', 'Philippine Peso (₱)'), ('IDR', 'Indonesian Rupiah (Rp)')], default='USD', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('investment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_cryptocurrency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.cryptocurrency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cryptocurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cryptocurrency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
