# Generated by Django 5.2 on 2025-05-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_signalplan_useraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercopytrade',
            name='copy_trade',
        ),
        migrations.AlterUniqueTogether(
            name='copytradersubscription',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='copytradersubscription',
            name='trader',
        ),
        migrations.RemoveField(
            model_name='copytradersubscription',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usercopytrade',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='signal_plan',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='target_plan',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usercopytrade',
            name='user',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='copy_trading_balance',
            new_name='bonus',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='investment_balance',
            new_name='investment',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='loss',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='trading_balance',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('NGN', 'Nigerian Naira (₦)'), ('GHS', 'Ghanaian Cedi (₵)'), ('KES', 'Kenyan Shilling (KSh)'), ('ZAR', 'South African Rand (R)'), ('INR', 'Indian Rupee (₹)'), ('AUD', 'Australian Dollar (A$)'), ('CAD', 'Canadian Dollar (C$)')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('investment', 'Investment'), ('profit', 'Profit Payment'), ('bonus', 'Bonus Payment')], max_length=20),
        ),
        migrations.DeleteModel(
            name='CopyTrade',
        ),
        migrations.DeleteModel(
            name='Trader',
        ),
        migrations.DeleteModel(
            name='CopyTraderSubscription',
        ),
        migrations.DeleteModel(
            name='SignalPlan',
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
        migrations.DeleteModel(
            name='UserAction',
        ),
        migrations.DeleteModel(
            name='UserCopyTrade',
        ),
    ]
