# Generated by Django 5.2 on 2025-05-28 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sitesettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentplan',
            old_name='profit_percentage',
            new_name='roi_percentage',
        ),
    ]
