# Generated by Django 5.2 on 2025-05-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_profit_percentage_investmentplan_roi_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
